### PR TITLE
Make skip slow tests the default behavior

### PR DESCRIPTION
**Pull request by l2yao**
*Issue #, if available:*
running slow tests as a default now

*Description of changes:*
make skip slow tests the default behavior

*Testing done:*
tox

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [ ] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-experiments/blob/master/CONTRIBUTING.md) doc
- [ ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-experiments/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-experiments/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-experiments/tree/master/doc) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by danabens** [comment]
how are you running tests currently? this is already the default behavior if you are using tox
https://github.com/aws/sagemaker-experiments/blob/master/tox.ini#L52

**Comment by l2yao** [comment]
> how are you running tests currently? this is already the default behavior if you are using tox
> https://github.com/aws/sagemaker-experiments/blob/master/tox.ini#L52

Yes, this is meant for the case of running pytest directly

**Comment by danabens** [comment]
update the tox ini then so we are not controlling slow test runs in two difference places

https://github.com/aws/sagemaker-experiments/blob/master/tox.ini#L52
https://github.com/aws/sagemaker-experiments/blob/master/tox.ini#L98

**Comment by l2yao** [comment]
> update the tox ini then so we are not controlling slow test runs in two difference places
> 
> https://github.com/aws/sagemaker-experiments/blob/master/tox.ini#L52
> https://github.com/aws/sagemaker-experiments/blob/master/tox.ini#L98

Done, here is the Action workflow run successfully for integ tests

**Pull request merged**
